### ISSUE TITLE
Support for koalas

### ISSUE THREAD

**Issue by M9T** [tkrabel/bamboolib#11]
Would be great to support koalas framework: https://github.com/databricks/koalas

**Comment by 8080labs** [comment]
Hi, thank you for your suggestion. We were already waiting for someone to suggest/request this feature :) Indeed, it won't be too hard to support koalas and we would love to offer koalas support. If you are willing to become a reference user for the koalas feature, please reach out to me via florian@8080labs.com

**Comment by tkrabel** [comment]
Closed due to inactivity. Please re-open if the issue comes up again :)
