### ISSUE TITLE
[Docs] Test instructions page might be a bit more helpful with a screenshot or two

### ISSUE THREAD

**Issue by neomatrix369** [tkrabel/bamboolib#14]
### Environment
N/A

### Description of Issue

When using the https://github.com/tkrabel/bamboolib/blob/master/installation/bamboolib_test_run/without_virtual_environment.md#test-the-library, I found that the screenshot mentioned is missing, best to help the user with possible screenshots of GUIs they are expected to see.

### Reproduction Steps

Check docs in https://github.com/tkrabel/bamboolib/blob/master/installation/bamboolib_test_run/without_virtual_environment.md#test-the-library

### What steps have you taken to resolve this already?

Still going through the docs to find out what the GUI should look like.

**Comment by tkrabel** [comment]
@neomatrix369 thanks for the active feedback :)

I will add those asap :)
