### ISSUE TITLE
[Docs] Where to key in the license key once provided?

### ISSUE THREAD

**Issue by neomatrix369** [tkrabel/bamboolib#15]
### Environment

N/A

### Description of Issue

Received an email with the license key but no instructions on where to add this key, do we save this into some file for bamboolib to pick?

I also didn't see any direct docs on the repo or site leading me to instructions on how to use the license key.

### What steps have you taken to resolve this already?

Raising this issue and possibly chatting to one of the creators/maintainers of the project

**Comment by neomatrix369** [comment]
I found two links:

- [How to change your license key](https://docs.bamboolib.8080labs.com/documentation/how-tos/installation-and-setup/how-to-change-your-license-key)
- [How to upgrade your license during the trial](https://docs.bamboolib.8080labs.com/documentation/how-tos/installation-and-setup/how-to-upgrade-during-trial)

It would help if these were available under various places across the GitHub repo and/or docs and also sent out via email to anyone receiving licenses.

**Comment by neomatrix369** [comment]
On following the instructions in the notebook, I get the below message:
![Screen Shot 2020-03-13 at 12 54 12](https://user-images.githubusercontent.com/1570917/76622667-d9c74080-6529-11ea-949e-8de1fa5dfdde.png)

Can't see a prompt that allows me to enter my license.

Then I tried using the Python REPL to do that and I get the below:

```
Python 3.7.2 (default, Dec 29 2018, 00:00:04)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bamboolib as bam
bam.activa>>> bam.activate_license()
VBox(children=(HTML(value='\n<h2>bamboolib activation</h2>\nPlease enter your license key.<br>\n<br>\n'), VBox(children=(Text(value='', placeholder='Email', _dom_classes=('bamboolib-input',)), Text(value='', placeholder='License key', _dom_classes=('bamboolib-input',)), HBox(children=(Checkbox(value=False, indent=False, layout=Layout(width='15px')), HTML(value='I read and accept the <a href="https://bamboolib.com/eula" target=_blank class="bamboolib-link">terms and conditions</a>'))), HBox(children=(Button(button_style='success', description='Submit', disabled=True, icon='check', style=ButtonStyle(), tooltip='Submit', _dom_classes=('bamboolib-btn-primary-bold',)),))))))
>>>
``` 

It's possible it's trying to render something and is failing. I will try to get this working in the docker container.

**Comment by neomatrix369** [comment]
@tkrabel Any feedback for the above, this is the last issue to tackle, its between me and bamboolib 🤣

**Comment by 8080labs** [comment]
@neomatrix369 So close! :)
It seems that the Jupyter notebook extensions haven't been installed correctly. 
Can you solve the issue with help of [this link](https://docs.bamboolib.8080labs.com/documentation/how-tos/installation-and-setup/update-to-a-new-version-of-bamboolib/jupyter-notebook)?

**Comment by neomatrix369** [comment]
> @neomatrix369 So close! :)
> It seems that the Jupyter notebook extensions haven't been installed correctly.
> Can you solve the issue with help of [this link](https://docs.bamboolib.8080labs.com/documentation/how-tos/installation-and-setup/update-to-a-new-version-of-bamboolib/jupyter-notebook)?

I have run all of them a few times now. I will try both Jupyter notebook and Jupyter labs - it seems as you said Jupyter notebook support is better but I have a lot of work in Jupyter labs. Maybe I can cross-use them.

**Comment by 8080labs** [comment]
Everything should work in Jupyter Lab as well. If you want we can have a quick call about it and get it to work with your setup. We just need to nail the installation.

**Comment by neomatrix369** [comment]
> Everything should work in Jupyter Lab as well. If you want we can have a quick call about it and get it to work with your setup. We just need to nail the installation.

Works both in Jupyter Lab and Notebook, so it's all good now.

We can close this issue if you have been able to action any of the suggestions on this issue.
My suggestions for nailing the installation with be things we spoke of so far.

- Docker container (from dockerhub or via build/run script)
- one installer script (python + shell based would be best) to install natively
- less instructions to read but more installer program driven
- you can gather information of failed installation for git issue creation
- users can contribute nuances at various levels via the above
- one place to find them all (all linking to the docs from here and website)

**Comment by 8080labs** [comment]
Ok, perfect. We will leave it open as some inspiration for future adjustments
