### ISSUE TITLE
[Troubleshooting] ModuleNotFound [...jupyter/...] when trying to build Jupterlab

### ISSUE THREAD

**Issue by neomatrix369** [tkrabel/bamboolib#18]
### Environment

* Operating System: `macos`
* Python Version: `3.7.2`
* How did you install bamboolib:  `pip`
* Python packages: see issue https://github.com/tkrabel/bamboolib/issues/13
* If bamboolib is used with JupyterLab: JupyterLab extensions: `jupyter labextension list`
see issue https://github.com/tkrabel/bamboolib/issues/13
* If bamboolib is used with Jupyter Notebook: Notebook extension: `jupyter nbextension list`
see issue https://github.com/tkrabel/bamboolib/issues/13

### Description of Issue

The details are mentioned in issue see issue https://github.com/tkrabel/bamboolib/issues/13, although repeating the specific problem see this message on the Jupyter Lab Gitter Channel: https://gitter.im/jupyterlab/jupyterlab?at=5e4711fa46e99d431f78c53d

I was installing `bamboolib` on my macOS and expected the installation to go smooth but it seems some other package might be conflicting after performing the last steps at [installation steps](https://github.com/tkrabel/bamboolib/blob/master/installation/no_virtual_environment/installation.md#22-jupyter-lab-10) - I got this error message:
```
[LabBuildApp] JupyterLab 1.2.7
[LabBuildApp] Building in /Users/swami/.local/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod)
[LabBuildApp] WARNING | The extension "nbdime-jupyterlab" is outdated.

An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /var/folders/lv/qn495mln6h79dkh4b6j3rclm0000gn/T/jupyterlab-debug-1u0e_k9s.log
```

Looking into the logs shows me:
```
...
[LabBuildApp] > node /Users/swami/.local/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod
[LabBuildApp] yarn run v1.15.2
$ ensure-max-old-space webpack --config webpack.prod.config.js
ModuleNotFoundError: Module not found: Error: Can't resolve 'es6-promise/auto' in ...
...
```

As per the gitter discussions, it appears a version of plotly lab extension conflicts when trying to build the lab extensions, more details in the section below.

### Reproduction Steps

This one might be hard to reproduce as it's user specific, but hopefully, the attached log file might prove it:

[jupyterlab-debug-1u0e_k9s.log](https://github.com/tkrabel/bamboolib/files/4329059/jupyterlab-debug-1u0e_k9s.log)

Also this message on the `gitter` channel of `jupyterlabs`: https://gitter.im/jupyterlab/jupyterlab?at=5e4711fa46e99d431f78c53d (search for the messages around `ModuleNotFoundError: Module not found: Error: Can't resolve 'es6-promise/auto' in '/opt/conda/share/jupyter/lab/staging/build`

### What steps have you taken to resolve this already?

I did the following and the error went away, and I was able to rebuild the `jupyterlab` extensions:

```
cd /path/to/.local/share/jupyter/lab/staging/
npm install jupyterlab-plotly
npm install jupyterlab-chart-editor
npm install bamboolib
npm install nbdime-jupyterlab
npm install @8080labs/qgrid@1.1.1
npm install qgrid
npm install plotlywidget
npm install @8080labs/qgrid
npm install @jupyter-widgets/jupyterlab-manager
npm install @jupyterlab/coreutils
npm install @jupyterlab/application
npm install es6-promise@^3.0.2 es6-promise@~4.2.6
npm install
jupyter lab build --minimize=False
```

**Comment by tkrabel** [comment]
Hi @neomatrix369,

Looking at your looks, the root of the error was that the JupyterLab extentsion "nbdime-jupyterlab" was outdated. I think a `jupyter labextension install nbdime-jupyterlab` would have been enough to fix the issue.

Please note that things work way smoother with Jupyter Notebook. That's mainly because JupyterLab as a platform is evolving a lot and therefore lacks some stability atm.

**Comment by neomatrix369** [comment]
> Hi @neomatrix369,
> 
> Looking at your looks, the root of the error was that the JupyterLab extentsion "nbdime-jupyterlab" was outdated. I think a `jupyter labextension install nbdime-jupyterlab` would have been enough to fix the issue.
> 
> Please note that things work way smoother with Jupyter Notebook. That's mainly because JupyterLab as a platform is evolving a lot and therefore lacks some stability atm.

I'm not sure that is correct, I did update the `nbdime-jupyterlab` and it didn't still build. Although the issue is now gone away.
