### ISSUE TITLE
Please add the Pypi/pip and Conda commands for installation

### ISSUE THREAD

**Issue by ssameerr** [tkrabel/bamboolib#2]
Hi,

README : Please add the Pypi/pip and Conda commands for installation

Thanks,
Sameer

**Comment by GajjarMihir** [comment]
Hello @ssameerr . I found a similar issue in the closed issue section. I guess this package is yet to be released. One can find [bamboo-lib package](https://pypi.org/project/bamboo-lib/#description) on google which can be installed with pip but I guess it is a different package. Hope this helps address this issue.
