### ISSUE TITLE
Feature idea - bamboolib cell type

### ISSUE THREAD

**Issue by ghost** [tkrabel/bamboolib#24]
It's an anti-pattern making transformations in an output cell and overriding the df rendering.

Could you make the bamboolib UI a cell type, similar to a markdown or code cell? 

Flow:
- User would create a new cell.
- Change it to be a bamboolib cell type.
- Specify the name of their df.
- Make transformations.
- See the head() in an output cell.

**Comment by FlorianWetschoreck** [comment]
Hi Layne,

thank you for reaching out and thinking about how to make bamboolib better.
Before I reply with my view, I would like to understand a little bit better why you think that the current approach is an anti-pattern. And which anti-pattern you mean by that?

Thank you,
Florian
