### ISSUE TITLE
I was trying to run the test  installation bamboolib   as suggested but it failed

### ISSUE THREAD

**Issue by KVSSetty** [tkrabel/bamboolib#25]
### Environment

* Operating System:
windows10
* Python Version: `$ python --version`
3.7
* How did you install bamboolib: (`pip`, `conda`, or `other (please explain)`)
 using conda, as per the instruction page on your site.
* Python packages: `$ pip list` or `$ conda list` (please include bamboolib)
# packages in environment at C:\Users\kvsse\anaconda3\envs\bamboolibenv:
#
# Name                    Version                   Build  Channel
argon2-cffi               20.1.0           py37he774522_1
async_generator           1.10             py37h28b3542_0
attrs                     20.3.0             pyhd3eb1b0_0
backcall                  0.2.0                      py_0
bleach                    3.2.1                      py_0
brotlipy                  0.7.0           py37he774522_1000
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hf50a25e_2    conda-forge
cffi                      1.14.3           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
colorama                  0.4.4                      py_0
cryptography              3.1.1            py37h7a1dbc1_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
entrypoints               0.3                      py37_0
icu                       58.2                 ha925a31_3
idna                      2.10                       py_0
importlib-metadata        2.0.0                      py_1
importlib_metadata        2.0.0                         1
intel-openmp              2020.2                      254
ipykernel                 5.3.4            py37h5ca1d4c_0
ipython                   7.19.0           py37hd4e2768_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_1
jedi                      0.17.2                   py37_0
jinja2                    2.11.2                     py_0
jpeg                      9b                   hb83a4c4_2
json5                     0.9.5                      py_0
jsonschema                3.2.0                      py_2
jupyter                   1.0.0                    py37_7
jupyter_client            6.1.7                      py_0
jupyter_console           6.2.0                      py_0
jupyter_core              4.6.3                    py37_0
jupyterlab                2.2.6                      py_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         1.2.0                      py_0
libblas                   3.8.0                    20_mkl    conda-forge
libcblas                  3.8.0                    20_mkl    conda-forge
liblapack                 3.8.0                    20_mkl    conda-forge
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37hfa6e2cd_1
mistune                   0.8.4           py37hfa6e2cd_1001
mkl                       2020.2                      256
msys2-conda-epoch         20160418                      1
nbclient                  0.5.1                      py_0
nbconvert                 6.0.7                    py37_0
nbformat                  5.0.8                      py_0
nest-asyncio              1.4.1                      py_0
notebook                  6.1.4                    py37_0
numpy                     1.19.4           py37hd20adf4_1    conda-forge
openssl                   1.1.1h               he774522_0    conda-forge
packaging                 20.4                       py_0
pandoc                    2.11                 h9490d1a_0
pandocfilters             1.4.2                    py37_1
parso                     0.7.0                      py_0
pickleshare               0.7.5                 py37_1001
pip                       20.2.4           py37haa95532_0
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.8                      py_0
prompt_toolkit            3.0.8                         0
pycparser                 2.20                       py_2
pygments                  2.7.2              pyhd3eb1b0_0
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py37h6538335_2
pyrsistent                0.17.3           py37he774522_0
pysocks                   1.7.1                    py37_1
python                    3.7.9                h60c2a47_0
python-dateutil           2.8.1                      py_0
python_abi                3.7                     1_cp37m    conda-forge
pywin32                   227              py37he774522_1
pywinpty                  0.5.7                    py37_0
pyzmq                     19.0.2           py37ha925a31_1
qt                        5.9.7            vc14h73c81de_0
qtconsole                 4.7.7                      py_0
qtpy                      1.9.0                      py_0
requests                  2.24.0                     py_0
send2trash                1.5.0                    py37_0
setuptools                50.3.1           py37haa95532_1
sip                       4.19.8           py37h6538335_0
six                       1.15.0                     py_0
sqlite                    3.33.0               h2a8f88b_0
terminado                 0.9.1                    py37_0
testpath                  0.4.4                      py_0
tornado                   6.0.4            py37he774522_1
traitlets                 5.0.5                      py_0
urllib3                   1.25.11                    py_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
wheel                     0.35.1                     py_0
widgetsnbextension        3.5.1                    py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
zeromq                    4.3.2                ha925a31_3
zipp                      3.4.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4

(bamboolibenv) C:\Users\kvsse>

* If bamboolib is used with JupyterLab: JupyterLab extensions: `jupyter labextension list`
(bamboolibenv) C:\Users\kvsse>jupyter labextension list
JupyterLab v2.2.6
No installed extensions
* If bamboolib is used with Jupyter Notebook: Notebook extension: `jupyter nbextension list`

### Description of Issue

* What did you expect to happen?
suppose to display pandas dataframe with your app button
* What happened instead/
displayed this message
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-98d62baa4c65> in <module>
----> 1 import bamboolib as bam
      2 import pandas as pd
      3 df = pd.read_csv(bam.titanic_csv)
      4 df

~\AppData\Roaming\Python\Python37\site-packages\bamboolib\__init__.py in <module>
     17 # NOTE: you can think about removing this if we require matplotlib>3.3.1
     18 try:
---> 19     import seaborn
     20 except ImportError as import_error:
     21     if "DLL load failed" in str(import_error):

~\AppData\Roaming\Python\Python37\site-packages\seaborn\__init__.py in <module>
      1 # Capture the original matplotlib rcParams
----> 2 import matplotlib as mpl
      3 _orig_rc_params = mpl.rcParams.copy()
      4 
      5 # Import seaborn objects

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\__init__.py in <module>
    105 # cbook must import matplotlib only within function
    106 # definitions, so it is safe to import from it here.
--> 107 from . import cbook, rcsetup
    108 from matplotlib.cbook import MatplotlibDeprecationWarning, sanitize_sequence
    109 from matplotlib.cbook import mplDeprecation  # deprecated

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\cbook\__init__.py in <module>
     26 import weakref
     27 
---> 28 import numpy as np
     29 
     30 import matplotlib

~\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py in <module>
    303 
    304     if sys.platform == "win32" and sys.maxsize > 2**32:
--> 305         _win_os_check()
    306 
    307     del _win_os_check

~\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py in _win_os_check()
    300                    "See this issue for more information: "
    301                    "https://tinyurl.com/y3dm3h86")
--> 302             raise RuntimeError(msg.format(__file__)) from None
    303 
    304     if sys.platform == "win32" and sys.maxsize > 2**32:

RuntimeError: The current Numpy installation ('C:\\Users\\kvsse\\AppData\\Roaming\\Python\\Python37\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

### Reproduction Steps

1.
2.
3.
...

### What steps have you taken to resolve this already?
installed the latest version of numpy and tried the same error

...

### Anything else?

...

**Comment by tkrabel** [comment]
Hi @KVSSetty - Thanks for the notice!

We should've fixed this issue by now. Can you confirm it works?

I'll reopen the issue if it still doesn't work.

Cheers,
Tobias
