### ISSUE TITLE
Python 3.9

### ISSUE THREAD

**Issue by Bidek56** [tkrabel/bamboolib#27]
### Environment

* Operating System: Windows
* Python Version: 3.9.2
* How did you install bamboolib: pip

### Description of Issue
ERROR: Could not find a version that satisfies the requirement bamboolib
ERROR: No matching distribution found for bamboolib

### Reproduction Steps

1. pip install bamboolib

Please upgrade bamboolib to support Python >= 3.9. Thanks

**Comment by tkrabel** [comment]
Hi @Bidek56 - Thanks for the request. 

We'll work on it!

**Comment by tkrabel** [comment]
Python 3.9 is supported as of May 4th. 👍
