### ISSUE TITLE
pip install bamboo-lib is not working

### ISSUE THREAD

**Issue by Aishwarya2203** [tkrabel/bamboolib#3]
pip install bamboo-lib is not working
Also how do i pull this and install the gui

**Comment by GajjarMihir** [comment]
Hello @Aishwarya2203, I was curious to explore bamboolib as soon as I saw a video about it - the package that can be used to manipulate Pandas Dataframe with GUI. I think you are trying to do the same. However I found that bamboolib is not released yet only a preview video is available. The command you are executing is for [a different package](https://pypi.org/project/bamboo-lib/#description). I even found the same when I searched it on Google but I think it is a different package. Hope you find this helpful.

**Comment by gitjuanfmunoz** [comment]
$ pip install bamboolib
Collecting bamboolib
  Could not fetch URL https://pypi.python.org/simple/bamboolib/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping
  Could not find a version that satisfies the requirement bamboolib (from versions: )
No matching distribution found for bamboolib
