### ISSUE TITLE
[Bug] Filtering Rows by datetime not working

### ISSUE THREAD

**Issue by punnkrit** [tkrabel/bamboolib#30]
Please see attached image for reference
![image](https://user-images.githubusercontent.com/67582908/123154016-8fed3a00-d490-11eb-83fa-ed39dee368a0.png)
![image](https://user-images.githubusercontent.com/67582908/123154819-8d3f1480-d491-11eb-8808-be920c0b1206.png)

The images above should be self-explanatory; I created a simple data frame with some data and dates, however, filtering/dropping rows by date is not working simply because there's no quotes between the column name.

I've tried filtering on some other data types as well, and weirdly enough, this bug occurs only for datetime for me.

Hope this get fixed soon, this library is superbly useful and I can't wait to show my colleagues 😊

**Comment by FlorianWetschoreck** [comment]
Thank you for the issue! I fixed this and it will be part of the next release. Most likely (not coming but) next Friday!
