### ISSUE TITLE
Bamboolib source

### ISSUE THREAD

**Issue by astrojuanlu** [tkrabel/bamboolib#33]
Hi! Just discovered this after reading the announcement about the acquisition by Databricks. Congrats :)

It is my understanding that this repository contains a README with some pointers and a few plugins, but not the actual source code of bamboolib. Is that correct?

**Comment by FlorianWetschoreck** [comment]
Thank you for the congrats and your understanding is correct :)

**Comment by astrojuanlu** [comment]
Thanks for the quick turnaround!
