### ISSUE TITLE
Is there a license associated with this project?

### ISSUE THREAD

**Issue by ghost** [tkrabel/bamboolib#35]
Hi, is there a license associated with this project?  It seems great and I would like to use it but am concerned about using it in a professional context.  Thanks!

**Comment by almereyda** [comment]
It seems this project has been sold, and is not developed actively anymore.

See the link in #36 for details.

It would be nice of them to release the last known working version as FLOSS, though, so the community can fork and continue the module.

**Comment by FlorianWetschoreck** [comment]
Thanks @almereyda  I updated the readme to better communicate the fact that bamboolib was never open-source. The code was always proprietary. As of now, there are no plans to release a FLOSS version, though.

@TriumphTodd The software was released under terms that (did) allow for work in professional context. Please note the announcement that we joined Databricks.

**Comment by ghost** [comment]
@FlorianWetschoreck OK, that's disappointing but thank you for clarifying.
