### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by jgdpsingh** [tkrabel/bamboolib#39]
I am using Windows 8.1 pro and latest Visual C++ installed. I've tried installing it in Anaconda as well as Kaggle but this same error keeps
popping up

"Collecting bamboolib
  Downloading bamboolib-1.30.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (8.2 MB)
     |████████████████████████████████| 8.2 MB 13.1 MB/s            
Collecting plotly<5.0.0,>=4.9.0
  Downloading plotly-4.14.3-py2.py3-none-any.whl (13.2 MB)
     |████████████████████████████████| 13.2 MB 63.1 MB/s            
Requirement already satisfied: scikit-learn<2.0.0,>=0.20.2 in /opt/conda/lib/python3.7/site-packages (from bamboolib) (0.23.2)
Collecting xlrd>=1.0.0
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 2.8 MB/s             
Requirement already satisfied: psutil<6,>=5.4.2 in /opt/conda/lib/python3.7/site-packages (from bamboolib) (5.8.0)
Requirement already satisfied: pandas<2.0.0,>=1.1.0 in /opt/conda/lib/python3.7/site-packages (from bamboolib) (1.3.5)
Requirement already satisfied: packaging>=19.2 in /opt/conda/lib/python3.7/site-packages (from bamboolib) (21.3)
Requirement already satisfied: jedi<1.0.0 in /opt/conda/lib/python3.7/site-packages (from bamboolib) (0.18.1)
Requirement already satisfied: pygments in /opt/conda/lib/python3.7/site-packages (from bamboolib) (2.10.0)
Requirement already satisfied: toml>=0.10.0 in /opt/conda/lib/python3.7/site-packages (from bamboolib) (0.10.2)
Collecting seaborn<0.11,>=0.10
  Downloading seaborn-0.10.1-py3-none-any.whl (215 kB)
     |████████████████████████████████| 215 kB 25.6 MB/s            
Requirement already satisfied: statsmodels<1.0.0 in /opt/conda/lib/python3.7/site-packages (from bamboolib) (0.13.1)
Collecting ipyslickgrid==0.0.3
  Downloading ipyslickgrid-0.0.3.tar.gz (51.4 MB)
     |████████████████████████████████| 51.4 MB 226 kB/s             
  Preparing metadata (setup.py) ... done
Collecting cryptography<3.0.0,>=2.6.1
  Downloading cryptography-2.9.2-cp35-abi3-manylinux2010_x86_64.whl (2.7 MB)
     |████████████████████████████████| 2.7 MB 26.2 MB/s            
Requirement already satisfied: ipywidgets<8.0.0,>=7.6.0 in /opt/conda/lib/python3.7/site-packages (from bamboolib) (7.6.5)
Requirement already satisfied: attrs>=20.3.0 in /opt/conda/lib/python3.7/site-packages (from bamboolib) (21.2.0)
Collecting ppscore<2.0.0,>=1.2.0
  Downloading ppscore-1.2.0.tar.gz (47 kB)
     |████████████████████████████████| 47 kB 2.8 MB/s             
  Preparing metadata (setup.py) ... done
Collecting analytics-python==1.2.9
  Downloading analytics_python-1.2.9-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: requests<3.0,>=2.7 in /opt/conda/lib/python3.7/site-packages (from analytics-python==1.2.9->bamboolib) (2.26.0)
Requirement already satisfied: python-dateutil>2.1 in /opt/conda/lib/python3.7/site-packages (from analytics-python==1.2.9->bamboolib) (2.8.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.7/site-packages (from analytics-python==1.2.9->bamboolib) (1.16.0)
Requirement already satisfied: notebook>=4.0.0 in /opt/conda/lib/python3.7/site-packages (from ipyslickgrid==0.0.3->bamboolib) (6.4.6)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /opt/conda/lib/python3.7/site-packages (from cryptography<3.0.0,>=2.6.1->bamboolib) (1.15.0)
Requirement already satisfied: nbformat>=4.2.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets<8.0.0,>=7.6.0->bamboolib) (5.1.3)
Requirement already satisfied: ipython-genutils~=0.2.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets<8.0.0,>=7.6.0->bamboolib) (0.2.0)
Requirement already satisfied: traitlets>=4.3.1 in /opt/conda/lib/python3.7/site-packages (from ipywidgets<8.0.0,>=7.6.0->bamboolib) (5.1.1)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets<8.0.0,>=7.6.0->bamboolib) (3.5.2)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets<8.0.0,>=7.6.0->bamboolib) (1.0.2)
Requirement already satisfied: ipython>=4.0.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets<8.0.0,>=7.6.0->bamboolib) (7.30.1)
Requirement already satisfied: ipykernel>=4.5.1 in /opt/conda/lib/python3.7/site-packages (from ipywidgets<8.0.0,>=7.6.0->bamboolib) (6.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/conda/lib/python3.7/site-packages (from jedi<1.0.0->bamboolib) (0.8.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.7/site-packages (from packaging>=19.2->bamboolib) (3.0.6)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas<2.0.0,>=1.1.0->bamboolib) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in /opt/conda/lib/python3.7/site-packages (from pandas<2.0.0,>=1.1.0->bamboolib) (1.20.3)
Requirement already satisfied: retrying>=1.3.3 in /opt/conda/lib/python3.7/site-packages (from plotly<5.0.0,>=4.9.0->bamboolib) (1.3.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from scikit-learn<2.0.0,>=0.20.2->bamboolib) (3.0.0)
Requirement already satisfied: joblib>=0.11 in /opt/conda/lib/python3.7/site-packages (from scikit-learn<2.0.0,>=0.20.2->bamboolib) (1.1.0)
Requirement already satisfied: scipy>=0.19.1 in /opt/conda/lib/python3.7/site-packages (from scikit-learn<2.0.0,>=0.20.2->bamboolib) (1.7.3)
Requirement already satisfied: matplotlib>=2.1.2 in /opt/conda/lib/python3.7/site-packages (from seaborn<0.11,>=0.10->bamboolib) (3.5.1)
Requirement already satisfied: patsy>=0.5.2 in /opt/conda/lib/python3.7/site-packages (from statsmodels<1.0.0->bamboolib) (0.5.2)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography<3.0.0,>=2.6.1->bamboolib) (2.21)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets<8.0.0,>=7.6.0->bamboolib) (1.5.1)
Requirement already satisfied: matplotlib-inline<0.2.0,>=0.1.0 in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets<8.0.0,>=7.6.0->bamboolib) (0.1.3)
Requirement already satisfied: tornado<7.0,>=4.2 in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets<8.0.0,>=7.6.0->bamboolib) (6.1)
Requirement already satisfied: importlib-metadata<5 in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets<8.0.0,>=7.6.0->bamboolib) (4.10.1)
Requirement already satisfied: argcomplete>=1.12.3 in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets<8.0.0,>=7.6.0->bamboolib) (1.12.3)
Requirement already satisfied: jupyter-client<8.0 in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets<8.0.0,>=7.6.0->bamboolib) (7.1.0)
Requirement already satisfied: decorator in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0->ipywidgets<8.0.0,>=7.6.0->bamboolib) (5.1.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0->ipywidgets<8.0.0,>=7.6.0->bamboolib) (3.0.24)
Requirement already satisfied: setuptools>=18.5 in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0->ipywidgets<8.0.0,>=7.6.0->bamboolib) (59.5.0)
Requirement already satisfied: pickleshare in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0->ipywidgets<8.0.0,>=7.6.0->bamboolib) (0.7.5)
Requirement already satisfied: backcall in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0->ipywidgets<8.0.0,>=7.6.0->bamboolib) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0->ipywidgets<8.0.0,>=7.6.0->bamboolib) (4.8.0)
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=2.1.2->seaborn<0.11,>=0.10->bamboolib) (8.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=2.1.2->seaborn<0.11,>=0.10->bamboolib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=2.1.2->seaborn<0.11,>=0.10->bamboolib) (4.28.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=2.1.2->seaborn<0.11,>=0.10->bamboolib) (1.3.2)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /opt/conda/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets<8.0.0,>=7.6.0->bamboolib) (4.3.1)
Requirement already satisfied: jupyter-core in /opt/conda/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets<8.0.0,>=7.6.0->bamboolib) (4.9.1)
Requirement already satisfied: argon2-cffi in /opt/conda/lib/python3.7/site-packages (from notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (21.1.0)
Requirement already satisfied: pyzmq>=17 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (22.3.0)
Requirement already satisfied: nest-asyncio>=1.5 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (1.5.4)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (3.0.3)
Requirement already satisfied: Send2Trash>=1.8.0 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (1.8.0)
Requirement already satisfied: nbconvert in /opt/conda/lib/python3.7/site-packages (from notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (6.3.0)
Requirement already satisfied: prometheus-client in /opt/conda/lib/python3.7/site-packages (from notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (0.12.0)
Requirement already satisfied: terminado>=0.8.3 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (0.12.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests<3.0,>=2.7->analytics-python==1.2.9->bamboolib) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests<3.0,>=2.7->analytics-python==1.2.9->bamboolib) (3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests<3.0,>=2.7->analytics-python==1.2.9->bamboolib) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/conda/lib/python3.7/site-packages (from requests<3.0,>=2.7->analytics-python==1.2.9->bamboolib) (2.0.9)
Requirement already satisfied: typing-extensions>=3.6.4 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata<5->ipykernel>=4.5.1->ipywidgets<8.0.0,>=7.6.0->bamboolib) (4.0.1)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata<5->ipykernel>=4.5.1->ipywidgets<8.0.0,>=7.6.0->bamboolib) (3.6.0)
Requirement already satisfied: importlib-resources>=1.4.0 in /opt/conda/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets<8.0.0,>=7.6.0->bamboolib) (5.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /opt/conda/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets<8.0.0,>=7.6.0->bamboolib) (0.18.0)
Requirement already satisfied: entrypoints in /opt/conda/lib/python3.7/site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets<8.0.0,>=7.6.0->bamboolib) (0.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.7/site-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets<8.0.0,>=7.6.0->bamboolib) (0.7.0)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets<8.0.0,>=7.6.0->bamboolib) (0.2.5)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.7/site-packages (from jinja2->notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (2.0.1)
Requirement already satisfied: defusedxml in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (0.7.1)
Requirement already satisfied: bleach in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (4.1.0)
Requirement already satisfied: jupyterlab-pygments in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (0.1.2)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (0.5.9)
Requirement already satisfied: testpath in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (0.5.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (0.8.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (1.5.0)
Requirement already satisfied: webencodings in /opt/conda/lib/python3.7/site-packages (from bleach->nbconvert->notebook>=4.0.0->ipyslickgrid==0.0.3->bamboolib) (0.5.1)
Building wheels for collected packages: ipyslickgrid, ppscore
  Building wheel for ipyslickgrid (setup.py) ... done
  Created wheel for ipyslickgrid: filename=ipyslickgrid-0.0.3-py2.py3-none-any.whl size=1823285 sha256=ff5626c97e25d645e6119746097866fde3d3aebef00851fac2bfb9f29191c798
  Stored in directory: /root/.cache/pip/wheels/1a/a3/58/9c30cef9afebb4ca9f1e892e9245d676de3c2ae6e214e0781d
  Building wheel for ppscore (setup.py) ... done
  Created wheel for ppscore: filename=ppscore-1.2.0-py2.py3-none-any.whl size=13068 sha256=f1b8ebe3c13f99afcce336007f4df05176ac78b418e506b6adc3c32be8784a2f
  Stored in directory: /root/.cache/pip/wheels/d2/3c/58/2ff786414b21713edc6f4fdb54fdee89ac37bca5edd1f60634
Successfully built ipyslickgrid ppscore
Installing collected packages: xlrd, seaborn, ppscore, plotly, ipyslickgrid, cryptography, analytics-python, bamboolib
  Attempting uninstall: seaborn
    Found existing installation: seaborn 0.11.2
    Uninstalling seaborn-0.11.2:
      Successfully uninstalled seaborn-0.11.2
  Attempting uninstall: plotly
    Found existing installation: plotly 5.5.0
    Uninstalling plotly-5.5.0:
      Successfully uninstalled plotly-5.5.0
  Attempting uninstall: cryptography
    Found existing installation: cryptography 36.0.1
    Uninstalling cryptography-36.0.1:
      Successfully uninstalled cryptography-36.0.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyopenssl 21.0.0 requires cryptography>=3.3, but you have cryptography 2.9.2 which is incompatible.
Successfully installed analytics-python-1.2.9 bamboolib-1.30.0 cryptography-2.9.2 ipyslickgrid-0.0.3 plotly-4.14.3 ppscore-1.2.0 seaborn-0.10.1 xlrd-2.0.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: [https://pip.pypa.io/warnings/venv](https://pip.pypa.io/warnings/venv%3C/span%3E)
Note: you may need to restart the kernel to use updated packages."

Kindly help

**Comment by fwetdb** [comment]
Please note that bamboolib has been acquired by Databricks and thus we don't provide onboarding support outside of databricks any more.
https://docs.bamboolib.8080labs.com/databricks

That being said, the installation looks fine to me. The error messages that you see do sometimes come up with pip but everything might work fine.
