### ISSUE TITLE
Bamboolib UI Not loading for colab

### ISSUE THREAD

**Issue by GJvignesh** [tkrabel/bamboolib#8]
### Environment

vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) CPU @ 2.00GHz
stepping	: 3
microcode	: 0x1
cpu MHz		: 2000.164
cache size	: 39424 KB
Python 3.0

### Description of Issue

Bamboolib UI not loading

### Reproduction Steps

import pandas as pd
! pip install bamboolib 
! pip install -U ipykernel
import bamboolib as bam
bam.enable()
df = pd.read_csv(".../file_path/...")
df

### What steps have you taken to resolve this already?

Not loading in Colab as of now

**Comment by tkrabel** [comment]
Hi there,

thanks for your issue report
Please note that bamboolib only supports Jupyter Notebook and JupyterLab atm. However, we are working on the support for Google Colab and are happy to let you know once we are ready.

Best,
Tobias

**Comment by JJ-BO** [comment]
Hello, is bamboolib for colab ready?

**Comment by JJ-BO** [comment]
> Hi there,
> 
> thanks for your issue report Please note that bamboolib only supports Jupyter Notebook and JupyterLab atm. However, we are working on the support for Google Colab and are happy to let you know once we are ready.
> 
> Best, Tobias

is there a way to have ba,boolib in colab?
