### ISSUE TITLE
Possible to use without Dockerfile?

### ISSUE THREAD

**Issue by matthewbegun** [tkrabel/bamboolib#9]
When attempting to add `bamboolib` to an existing open project for use on `mybinder` using a `requirements.txt` file or `pip` statement within an `environment.yml` file, `bamboolib` asks for a license code.

Is it not possible to use without a `Dockerfile` (for open source/data projects)? 

Followup - if it has to be in a `Dockerfile`, how can it be used from an image which is not based on a `Jupyter` pre-built stack?

Thanks,
Matt

**Comment by 8080labs** [comment]
Hi Matt,

sorry that I forgot about this issue.

Currently you can only use bamboolib on binder with the specified Dockerfile.
However, you can append custom requirements to the existing Dockerfile.

Have a great day,
Florian

**Comment by matthewbegun** [comment]
Ok thanks!
